---
- name: "mkcert | Unarchive the mkcert binary"
  unarchive:
    src: ../../offline_files/mkcert.tar.gz
    dest: /tmp/
    creates: /tmp/mkcert
  when: not ansible_check_mode 
- name: "mkcert | Install mkcert to /usr/local/bin"
  copy:
    src: /tmp/mkcert
    dest: /usr/local/bin/mkcert
    mode: '0755'
    remote_src: yes # This tells Ansible the source is on the remote machine
  args:
    creates: /usr/local/bin/mkcert # Won't run if the file already exists
  when: not ansible_check_mode 
- name: "mkcert | Create a local Certificate Authority (CA)"
  command: mkcert -install
  args:
    # The CA root key is usually stored in this path
    creates: "{{ ansible_env.HOME }}/.local/share/mkcert/rootCA.pem"

- name: "mkcert | Ensure SSL directory exists for Nginx"
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0700'
  when: not ansible_check_mode # <-- این شرط را اضافه کنید
 

- name: "mkcert | Generate wildcard SSL certificate for the domain"
  command: "mkcert '*.{{ domain_name }}'"
  args:
    chdir: /etc/nginx/ssl # Run the command inside this directory
    creates: "/etc/nginx/ssl/_wildcard.{{ domain_name }}.pem" # Won't run if cert exists
  notify: restart nginx # If we create a new cert, nginx should be restarted
  when: not ansible_check_mode
